### ISSUE TITLE
Read manga

### ISSUE THREAD

**Issue by ThangBK2009** [Mikunj/Ookami#7]
Please add feature read manga.

**Comment by Mikunj** [comment]
Hey @ThangBK2009, At the moment Ookami will not support reading manga from any unofficial sources. Maybe in the future if Kitsu offers these then i shall add it in.

**Comment by ThangBK2009** [comment]
Can you show me a framework to read manga in swift 3?

**Comment by Mikunj** [comment]
There don't seem to be any frameworks for that it seems. However if you are looking to read Manga on your iOS device there are plenty of apps that offer that functionality, a simple google search will help :)
